<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Bookgen plugins use netstandard 2.1 --> 
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- To use new language features and not limit to just C# 8.0 -->
    <LangVersion>latest</LangVersion>
    <!-- Important for plugin loadability -->
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Template.html" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookGen.Api\BookGen.Api.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>

</Project>
