<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Bookgen plugins use netstandard 2.1 -->
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- To use new language features and not limit to just C# 8.0 -->
    <LangVersion>latest</LangVersion>
    <!-- Important for plugin loadability -->
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <OutputPath>..\..\bin\sampleplugin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Template.html" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookGen.Api\BookGen.Api.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Update="manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="PackagePlugin" AfterTargets="Build">
    <PropertyGroup>
      <PluginPackage>$(OutputPath)..\..\$(Configuration)\plugins\$(AssemblyName).plugin</PluginPackage>
    </PropertyGroup>
    <ZipDirectory Overwrite="true" CompressionLevel="Optimal" SourceDirectory="$(TargetDir)" DestinationFile="$(PluginPackage)" />
  </Target>

</Project>
