//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/_errors/main.css&quot; /&gt;
        ///    &lt;title&gt;Error 404&lt;/title&gt;
        ///    &lt;style&gt;
        ///        html {
        ///            display: flex;
        ///            align-items: center;
        ///            justify-content: center;
        ///            height: 100vh;
        ///        }
        ///
        ///        body {
        ///            display: flex;
        ///            align-items: center;
        ///            justify-content: center;
        ///        }
        ///
        ///        #Error {
        ///            display: block;
        ///            vertical-align: mid [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookGen - Markdown to Book tool
        ///
        ///Usage: 
        ///    BookGen -a, --action [action] -d, --dir [directory]
        ///    BookGen -g, --gui -d, --dir [directory]
        ///
        ///Arguments:
        ///
        ///    -a, --action         Specify build action
        ///    -g, --gui            Start in gui mode.
        ///    -d, --dir            Specity working directory
        ///    
        ///Supported Actions:
        ///
        ///    Test
        ///        Build website with test params &amp; runs it in browser
        ///        
        ///    BuildPrint
        ///        Build printable html
        ///        
        ///    BuildEpub
        ///        Build epub documen [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ____              _     _____               _____       _ 
        /// |  _ \            | |   / ____|             / ____|     (_)
        /// | |_) | ___   ___ | | _| |  __  ___ _ __   | |  __ _   _ _ 
        /// |  _ &lt; / _ \ / _ \| |/ / | |_ |/ _ \ &apos;_ \  | | |_ | | | | |
        /// | |_) | (_) | (_) |   &lt;| |__| |  __/ | | | | |__| | |_| | |
        /// |____/ \___/ \___/|_|\_\\_____|\___|_| |_|  \_____|\__,_|_|
        ///                                                            
        ///                                                            .
        /// </summary>
        public static string Splash {
            get {
                return ResourceManager.GetString("Splash", resourceCulture);
            }
        }
    }
}
