//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/_errors/main.css&quot; /&gt;
        ///    &lt;title&gt;Error 404&lt;/title&gt;
        ///    &lt;style&gt;
        ///        html {
        ///            display: flex;
        ///            align-items: center;
        ///            justify-content: center;
        ///            height: 100vh;
        ///        }
        ///
        ///        body {
        ///            display: flex;
        ///            align-items: center;
        ///            justify-content: center;
        ///        }
        ///
        ///        #Error {
        ///            display: block;
        ///            vertical-align: mid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookGen - Markdown to Book tool
        ///
        ///Usage: BookGen -a [action] -d [directory]
        ///
        ///Supported Actions: -a or --action switch:
        ///	
        ///	buildweb
        ///		Builds website
        ///
        ///	testweb
        ///		Build website with test params &amp; runs it in browser
        ///
        ///	buildprint
        ///		Build printable html
        ///
        ///	createconfig
        ///		Create configuration file in directory, bookgen.json file
        ///
        ///	validateconfig
        ///		Validates configurarion file, bookgen.json and prints out a list of
        ///		issues in the config file, if there are.
        ///
        ///	clean
        ///		Clean output directory (nee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;.
        /// </summary>
        internal static string html5header {
            get {
                return ResourceManager.GetString("html5header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;jumbotron&quot;&gt;
        ///    &lt;h2&gt;[[0]]&lt;/h2&gt;
        ///    &lt;div class=&quot;form-group&quot;&gt;
        ///        &lt;input type=&quot;text&quot; id=&quot;searchtext&quot; autocomplete=&quot;off&quot; class=&quot;form-control&quot; placeholder=&quot;[[1]]&quot;&gt;
        ///        &lt;br/&gt;
        ///        &lt;button type=&quot;button&quot; id=&quot;searchbutton&quot; class=&quot;btn btn-primary&quot;&gt;[[2]]&lt;/button&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;
        ///&lt;div id=&quot;searchresults&quot;&gt;&lt;/div&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///    $(&quot;#searchbutton&quot;).click(function () {
        ///
        ///        var html = &quot;&quot;;
        ///        var matches = 0;
        ///        var terms = $(&quot;#searchtext&quot;).val();
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string searchform {
            get {
                return ResourceManager.GetString("searchform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot; &quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;.
        /// </summary>
        internal static string xhtmlheader {
            get {
                return ResourceManager.GetString("xhtmlheader", resourceCulture);
            }
        }
    }
}
