//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookgen.Template.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookgen.Template.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* PrismJS 1.15.0
        ///https://prismjs.com/download.html#themes=prism&amp;languages=markup+clike+csharp+batch+fsharp+json+python&amp;plugins=line-numbers */
        ////**
        /// * prism.js default theme for JavaScript, CSS and HTML
        /// * Based on dabblet (http://dabblet.com)
        /// * @author Lea Verou
        /// */
        ///
        ///code[class*=&quot;language-&quot;],
        ///pre[class*=&quot;language-&quot;] {
        ///	color: black;
        ///	background: none;
        ///	text-shadow: 0 1px white;
        ///	font-family: Consolas, Monaco, &apos;Andale Mono&apos;, &apos;Ubuntu Mono&apos;, monospace;
        ///	text-align: left;
        ///	white-space: pre;
        ///	w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PrismCss {
            get {
                return ResourceManager.GetString("PrismCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* PrismJS 1.15.0
        ///https://prismjs.com/download.html#themes=prism&amp;languages=markup+clike+csharp+batch+fsharp+json+python&amp;plugins=line-numbers */
        ///var _self=&quot;undefined&quot;!=typeof window?window:&quot;undefined&quot;!=typeof WorkerGlobalScope&amp;&amp;self instanceof WorkerGlobalScope?self:{},Prism=function(){var e=/\blang(?:uage)?-([\w-]+)\b/i,t=0,n=_self.Prism={manual:_self.Prism&amp;&amp;_self.Prism.manual,disableWorkerMessageHandler:_self.Prism&amp;&amp;_self.Prism.disableWorkerMessageHandler,util:{encode:function(e){return e instanceof a?ne [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PrismJs {
            get {
                return ResourceManager.GetString("PrismJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;jumbotron&quot;&gt;
        ///    &lt;h2&gt;[[0]]&lt;/h2&gt;
        ///    &lt;div class=&quot;form-group&quot;&gt;
        ///        &lt;input type=&quot;text&quot; id=&quot;searchtext&quot; autocomplete=&quot;off&quot; class=&quot;form-control&quot; placeholder=&quot;[[1]]&quot;&gt;
        ///        &lt;br/&gt;
        ///        &lt;button type=&quot;button&quot; id=&quot;searchbutton&quot; class=&quot;btn btn-primary&quot;&gt;[[2]]&lt;/button&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;
        ///&lt;div id=&quot;searchresults&quot;&gt;&lt;/div&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///    $(&quot;#searchbutton&quot;).click(function () {
        ///
        ///        var html = &quot;&quot;;
        ///        var matches = 0;
        ///        var terms = $(&quot;#searchtext&quot;).val();
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Searchform {
            get {
                return ResourceManager.GetString("Searchform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot; &quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string TemplateEpub {
            get {
                return ResourceManager.GetString("TemplateEpub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string TemplatePrint {
            get {
                return ResourceManager.GetString("TemplatePrint", resourceCulture);
            }
        }
    }
}
