//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cdg.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cdg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[Select current  directory ►]].
        /// </summary>
        internal static string _MenuSelectorCurrentDir_10 {
            get {
                return ResourceManager.GetString("_MenuSelectorCurrentDir_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[ Jump to home ~ ]].
        /// </summary>
        internal static string _MenuSelectorHomeDir_35 {
            get {
                return ResourceManager.GetString("_MenuSelectorHomeDir_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[Known Folders ?]].
        /// </summary>
        internal static string _MenuSelectorKnownDirs_40 {
            get {
                return ResourceManager.GetString("_MenuSelectorKnownDirs_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[Jump to root /]].
        /// </summary>
        internal static string _MenuSelectorRootDir_30 {
            get {
                return ResourceManager.GetString("_MenuSelectorRootDir_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[Up one directory ▲]].
        /// </summary>
        internal static string _MenuSelectorUpOneDir_20 {
            get {
                return ResourceManager.GetString("_MenuSelectorUpOneDir_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        internal static string GroupDirectories {
            get {
                return ResourceManager.GetString("GroupDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials.
        /// </summary>
        internal static string GroupSpecials {
            get {
                return ResourceManager.GetString("GroupSpecials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: {0}.
        /// </summary>
        internal static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        internal static string PathNameRootDir {
            get {
                return ResourceManager.GetString("PathNameRootDir", resourceCulture);
            }
        }
    }
}
