//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for {0}. Value must be between {1} and {2}.
        /// </summary>
        internal static string InvalidValueMustBeBetweenRange {
            get {
                return ResourceManager.GetString("InvalidValueMustBeBetweenRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for {0}. Value must be &gt; 0.
        /// </summary>
        internal static string InvalidValueMustBePositive {
            get {
                return ResourceManager.GetString("InvalidValueMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset file not found: {0}.
        /// </summary>
        internal static string MissingAsset {
            get {
                return ResourceManager.GetString("MissingAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets field not found in configuraton.
        /// </summary>
        internal static string MissingAssets {
            get {
                return ResourceManager.GetString("MissingAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Host name not set.
        /// </summary>
        internal static string MissingHostName {
            get {
                return ResourceManager.GetString("MissingHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image directory can&apos;t be found: {0}.
        /// </summary>
        internal static string MissingImageDir {
            get {
                return ResourceManager.GetString("MissingImageDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index page not configured.
        /// </summary>
        internal static string MissingIndex {
            get {
                return ResourceManager.GetString("MissingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata settings can&apos;t be found.  Possibly corrupted config?.
        /// </summary>
        internal static string MissingMetadata {
            get {
                return ResourceManager.GetString("MissingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrucpt Configuration File. Please create a new one.
        /// </summary>
        internal static string MissingSection {
            get {
                return ResourceManager.GetString("MissingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style class definitions can&apos;t be found. Possibly corrupted config?.
        /// </summary>
        internal static string MissingStyleClasses {
            get {
                return ResourceManager.GetString("MissingStyleClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file can&apos;t be found: {0}.
        /// </summary>
        internal static string MissingTemplateFile {
            get {
                return ResourceManager.GetString("MissingTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of Contents file not found: {0}.
        /// </summary>
        internal static string MissingTocFile {
            get {
                return ResourceManager.GetString("MissingTocFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name must end with a / char.
        /// </summary>
        internal static string MissingTrailingSlash {
            get {
                return ResourceManager.GetString("MissingTrailingSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations can&apos;t be found. Possibly corrupted config?.
        /// </summary>
        internal static string MissingTranslations {
            get {
                return ResourceManager.GetString("MissingTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file in toc doesn&apos;t exist: {0}.
        /// </summary>
        internal static string TOCFileNotExists {
            get {
                return ResourceManager.GetString("TOCFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path contains invalid chars: {0}. Valid chars: Numbers, letters, -, _.
        /// </summary>
        internal static string TOCInvalidFilePathChars {
            get {
                return ResourceManager.GetString("TOCInvalidFilePathChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOC file contains no chapters.
        /// </summary>
        internal static string TOCNoChapters {
            get {
                return ResourceManager.GetString("TOCNoChapters", resourceCulture);
            }
        }
    }
}
