//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/_errors/main.css&quot; /&gt;
        ///    &lt;title&gt;Error 404&lt;/title&gt;
        ///    &lt;style&gt;
        ///        html {
        ///            display: flex;
        ///            align-items: center;
        ///            justify-content: center;
        ///            height: 100vh;
        ///        }
        ///
        ///        body {
        ///            display: flex;
        ///            align-items: center;
        ///            justify-content: center;
        ///        }
        ///
        ///        #Error {
        ///            display: block;
        ///            vertical-align: mid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if
        ///then
        ///else
        ///elif
        ///fi
        ///case
        ///esac
        ///for
        ///select
        ///while
        ///until
        ///do
        ///done
        ///in
        ///function
        ///time
        ///{
        ///}
        ///!
        ///[[
        ///]]
        ///coproc.
        /// </summary>
        internal static string keywords_bash {
            get {
                return ResourceManager.GetString("keywords_bash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract
        ///as
        ///base
        ///bool
        ///add
        ///alias
        ///ascending
        ///async
        ///await
        ///by
        ///break
        ///byte
        ///case
        ///catch
        ///char
        ///checked
        ///class
        ///const
        ///continue
        ///decimal
        ///default
        ///delegate
        ///descending
        ///dynamic
        ///equals
        ///do
        ///double
        ///else
        ///enum
        ///event
        ///explicit
        ///extern
        ///false
        ///finally
        ///fixed
        ///float
        ///for
        ///foreach
        ///goto
        ///if
        ///implicit
        ///from
        ///get
        ///global
        ///group
        ///into
        ///join
        ///in
        ///int
        ///interface
        ///internal
        ///is
        ///lock
        ///long
        ///namespace
        ///let
        ///nameof
        ///on
        ///new
        ///null
        ///object
        ///operator
        ///orderby
        ///partial
        ///out
        ///override
        ///params
        ///private
        ///protected
        ///public
        ///readonly
        ///ref
        ///remove
        ///select
        ///set
        ///return
        ///sbyte
        ///sealed
        ///short
        ///sizeof
        ///stacka [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keywords_csharp {
            get {
                return ResourceManager.GetString("keywords_csharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;jumbotron&quot;&gt;
        ///    &lt;h2&gt;[[0]]&lt;/h2&gt;
        ///    &lt;div class=&quot;form-group&quot;&gt;
        ///        &lt;input type=&quot;text&quot; id=&quot;searchtext&quot; autocomplete=&quot;off&quot; class=&quot;form-control&quot; placeholder=&quot;[[1]]&quot;&gt;
        ///        &lt;button type=&quot;button&quot; id=&quot;searchbutton&quot; class=&quot;btn btn-primary&quot;&gt;[[2]]&lt;/button&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;
        ///&lt;div id=&quot;searchresults&quot;&gt;&lt;/div&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///    $(&quot;#searchbutton&quot;).click(function () {
        ///
        ///        var html = &quot;&quot;;
        ///        var matches = 0;
        ///        $(&quot;#searchresults&quot;).html(&quot;&quot;);
        ///
        ///        $(&quot;#searchcont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string searchform {
            get {
                return ResourceManager.GetString("searchform", resourceCulture);
            }
        }
    }
}
