//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookGen.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookGen.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets directory can&apos;t be found: {0}.
        /// </summary>
        internal static string MissingAssetsDir {
            get {
                return ResourceManager.GetString("MissingAssetsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Host name not set.
        /// </summary>
        internal static string MissingHostName {
            get {
                return ResourceManager.GetString("MissingHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image directory can&apos;t be found: {0}.
        /// </summary>
        internal static string MissingImageDir {
            get {
                return ResourceManager.GetString("MissingImageDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index page not configured.
        /// </summary>
        internal static string MissingIndex {
            get {
                return ResourceManager.GetString("MissingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata settings can&apos;t be found.  Possibly corrupted config?.
        /// </summary>
        internal static string MissingMetadata {
            get {
                return ResourceManager.GetString("MissingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precompile header settings can&apos;t be found.  Possibly corrupted config?.
        /// </summary>
        internal static string MissingPrecompile {
            get {
                return ResourceManager.GetString("MissingPrecompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search settings can&apos;t be found.  Possibly corrupted config?.
        /// </summary>
        internal static string MissingSearchOptions {
            get {
                return ResourceManager.GetString("MissingSearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search option texts can&apos;t be empty. One or more settings have emty values.
        /// </summary>
        internal static string MissingSearchOptionsText {
            get {
                return ResourceManager.GetString("MissingSearchOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style class definitions can&apos;t be found. Possibly corrupted config?.
        /// </summary>
        internal static string MissingStyleClasses {
            get {
                return ResourceManager.GetString("MissingStyleClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file can&apos;t be found: {0}.
        /// </summary>
        internal static string MissingTemplateFile {
            get {
                return ResourceManager.GetString("MissingTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of Contents file not found: {0}.
        /// </summary>
        internal static string MissingTocFile {
            get {
                return ResourceManager.GetString("MissingTocFile", resourceCulture);
            }
        }
    }
}
