//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookGen.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookGen.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build E-pub.
        /// </summary>
        internal static string ID_BuildEpub {
            get {
                return ResourceManager.GetString("ID_BuildEpub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build HTML for postprocess.
        /// </summary>
        internal static string ID_BuildPostProc {
            get {
                return ResourceManager.GetString("ID_BuildPostProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build printable html.
        /// </summary>
        internal static string ID_BuildPrint {
            get {
                return ResourceManager.GetString("ID_BuildPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build release website.
        /// </summary>
        internal static string ID_BuildRelease {
            get {
                return ResourceManager.GetString("ID_BuildRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build test website.
        /// </summary>
        internal static string ID_BuildTest {
            get {
                return ResourceManager.GetString("ID_BuildTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Wordpress export file.
        /// </summary>
        internal static string ID_BuildWordpress {
            get {
                return ResourceManager.GetString("ID_BuildWordpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean output directory.
        /// </summary>
        internal static string ID_ClearOutputDirectory {
            get {
                return ResourceManager.GetString("ID_ClearOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config in Json format.
        /// </summary>
        internal static string ID_ConfigJson {
            get {
                return ResourceManager.GetString("ID_ConfigJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config in yaml format.
        /// </summary>
        internal static string ID_ConfigYaml {
            get {
                return ResourceManager.GetString("ID_ConfigYaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create/overwrite configuration file?.
        /// </summary>
        internal static string ID_CreateConfig {
            get {
                return ResourceManager.GetString("ID_CreateConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create summary.md/overwrite and index.md files?.
        /// </summary>
        internal static string ID_CreateMdFiles {
            get {
                return ResourceManager.GetString("ID_CreateMdFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract/overwrite templates for customization?.
        /// </summary>
        internal static string ID_CreateTemplates {
            get {
                return ResourceManager.GetString("ID_CreateTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit program.
        /// </summary>
        internal static string ID_Exit {
            get {
                return ResourceManager.GetString("ID_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string ID_Help {
            get {
                return ResourceManager.GetString("ID_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start preview server.
        /// </summary>
        internal static string ID_PreviewServer {
            get {
                return ResourceManager.GetString("ID_PreviewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serve files.
        /// </summary>
        internal static string ID_Serve {
            get {
                return ResourceManager.GetString("ID_Serve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string ID_Stat {
            get {
                return ResourceManager.GetString("ID_Stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate config.
        /// </summary>
        internal static string ID_ValidateConfig {
            get {
                return ResourceManager.GetString("ID_ValidateConfig", resourceCulture);
            }
        }
    }
}
